Repository wecode-bootcamp-korea/30-2nd-WantU-backend, pull requests merged in 2022-03, with the labels that each got.

#1 [wantU] models.py 작성
  applications/__init__.py
  applications/admin.py
  applications/apps.py
  applications/migrations/0001_initial.py
  applications/migrations/__init__.py
  applications/models.py
  applications/tests.py
  applications/views.py
  cv/__init__.py
  cv/admin.py
  cv/apps.py
  cv/migrations/0001_initial.py
  cv/migrations/__init__.py
  cv/models.py
  cv/tests.py
  cv/views.py
  jobs/__init__.py
  jobs/admin.py
  jobs/apps.py
  jobs/migrations/0001_initial.py
  jobs/migrations/__init__.py
  jobs/models.py
  jobs/tests.py
  jobs/views.py
  users/__init__.py
  users/admin.py
  users/apps.py
  users/migrations/0001_initial.py
  users/migrations/__init__.py
  users/models.py
  users/tests.py
  users/views.py
  utils/time_stamp_model.py
  wantu/settings.py
Labels: Status: 수정 요청

#2 [이예솔] Modify: Modeling
  cv/models.py
  jobs/models.py
  users/models.py
Labels: Status: Accepted

#3 Modify: Modeling - migrated
  applications/migrations/0001_initial.py
  cv/migrations/0001_initial.py
  jobs/migrations/0001_initial.py
  users/migrations/0001_initial.py
Labels: Status: Accepted

#4 [이예솔]Create: users app >> kakao Login, login_decorator
  users/urls.py
  users/views.py
  utils/login_decorator.py
  wantu/urls.py
Labels: Status: Accepted

#5 [박영서] Create: s3 upload/download
  cv/urls.py
  cv/views.py
  wantu/settings.py
  wantu/urls.py
  박영서 (1).pdf
Labels: Status: Accepted

#7 [이예솔] Modify: modeling >> users kakao_email
  applications/migrations/0001_initial.py
  cv/migrations/0001_initial.py
  jobs/migrations/0001_initial.py
  users/migrations/0001_initial.py
  users/models.py
Labels: Status: 리뷰 요청

#6 [이예솔] Add: users app >> test.py kakaoLoginTest
  requirements.txt
  users/tests.py
  users/views.py
Labels: Status: 리뷰 요청

#8 [박영서] Add: S3 Feature Unit Test
  cv/tests.py
  cv/views.py
Labels: Status: 리뷰 요청

#9 [박영서] 모델링 수정 - uuid 컬럼 추가
  cv/migrations/0002_resume_uuid.py
  cv/models.py
Labels: Status: Accepted

#11 [박영서] resume 테이블에 is_deleted, deleted_at 컬럼 추가
  cv/migrations/0003_resume_deleted_at_resume_is_deleted.py
  cv/models.py
Labels: Status: 리뷰 요청

#10 [박영서] 이력서 이름변경, 삭제 , 리스트 API 및 테스트코드
  cv/migrations/0002_resume_uuid.py
  cv/migrations/0003_resume_deleted_at_resume_is_deleted.py
  cv/models.py
  cv/tests.py
  cv/urls.py
  cv/views.py
  s3_delete_outdated_file.py
  wantu/settings.py
Labels: Status: 리뷰 요청

#12 [박영서] 지원 현황 API 구현 및 테스트코드
  applications/tests.py
  applications/urls.py
  applications/views.py
  wantu/urls.py
  박영서 (1).pdf
Labels: Status: 리뷰 요청
